[versions]
accompanistSystemuicontroller = "0.36.0"
activityCompose = "1.11.0"
agp = "8.13.0"
animatedNavigationBar = "1.0.0"
coilCompose = "3.3.0"
firebaseAnalytics = "23.0.0"
firebaseBom = "34.4.0"
firebaseFunctionsKtxVersion = "21.2.1"
firebaseMessaging = "25.0.1"
hiltNavigationCompose = "1.3.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktorClientContentNegotiation = "3.3.3"
ktorClientCore = "3.3.3"
ktorClientLogging = "3.3.3"
ktorClientOkhttp = "3.3.3"
ktorSerializationKotlinxJson = "3.3.3"
lifecycleRuntimeKtx = "2.9.4"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
hiltAndroid="2.57.2"
material3 = "1.4.0"
materialIconsExtended = "1.7.8"
motiontoast = "1.4"
navigationCompose = "2.9.5"
foundation = "1.9.4"
firebaseFirestore = "26.0.2"
firebaseStorage = "22.0.1"
firebaseAuthKtx = "23.2.1"
firebaseAuth = "24.0.1"
streamChatAndroidClient = "6.27.0"
streamChatAndroidComposeUi = "6.27.0"
streamChatAndroidComposeVersion = "6.27.0"
streamChatAndroidOfflineVersion = "6.27.0"
streamChatAndroidState = "6.27.0"
streamChatAndroidUiComponents = "6.27.0"
streamVideoAndroidUiCompose = "1.16.0"
streamChatAndroidOffline = "7.7.0"
streamChatAndroidCompose = "7.7.0"
toasty = "1.5.2"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"
foundationLayout = "1.9.4"
firebaseFunctionsKtx = "21.1.2"
composeMaterial = "1.5.5"
uiGraphics = "1.9.5"
firebaseCrashlyticsBuildtools = "3.0.6"
foundationLayoutVersion = "1.10.0"


[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
animated-navigation-bar = { module = "com.exyte:animated-navigation-bar", version.ref = "animatedNavigationBar" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-functions-ktx-v2121 = { module = "com.google.firebase:firebase-functions-ktx", version.ref = "firebaseFunctionsKtxVersion" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid"}
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
motiontoast = { module = "com.github.Spikeysanju:MotionToast", version.ref = "motiontoast" }
stream-chat-android-client = { module = "io.getstream:stream-chat-android-client", version.ref = "streamChatAndroidClient" }
stream-chat-android-compose = { module = "io.getstream:stream-chat-android-compose", version.ref = "streamChatAndroidComposeVersion" }
stream-chat-android-compose-ui-v6270 = { module = "io.getstream:stream-chat-android-compose", version.ref = "streamChatAndroidComposeUi" }
stream-chat-android-offline-v6270 = { module = "io.getstream:stream-chat-android-offline", version.ref = "streamChatAndroidOfflineVersion" }
stream-chat-android-state = { module = "io.getstream:stream-chat-android-state", version.ref = "streamChatAndroidState" }
stream-chat-android-ui-components = { module = "io.getstream:stream-chat-android-ui-components", version.ref = "streamChatAndroidUiComponents" }
stream-video-android-ui-compose = { module = "io.getstream:stream-video-android-ui-compose", version.ref = "streamVideoAndroidUiCompose" }
stream-chat-android-offline = { module = "io.getstream:stream-chat-android-offline", version.ref = "streamChatAndroidOffline" }
stream-chat-android-compose-ui = { module = "io.getstream:stream-chat-android-compose-ui", version.ref = "streamChatAndroidCompose" }
toasty = { module = "com.github.GrenderG:Toasty", version.ref = "toasty" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
androidx-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
firebase-functions-ktx = { group = "com.google.firebase", name = "firebase-functions-ktx", version.ref = "firebaseFunctionsKtx" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
google-firebase-functions-ktx = { group = "com.google.firebase", name = "firebase-functions-ktx", version.ref = "firebaseFunctionsKtx" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayoutVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

